homepage:
    path:       /
    defaults:   { _controller: AppBundle:Default:index }
    
lucky_number:
    path:       /lucky/number
    defaults:   { _controller: AppBundle:Lucky:number }
    
article_list:
    path:       /articles/{_locale}/{page}.{_format}
    defaults:   { _controller: AppBundle:Article:list, page: 1, _locale: 'sr', _format: 'html' }
    requirements:
        page:       '\d+'
        _locale:    'en|sr|de'
        _format:    'html|rss'

article_create:
    path:       /article/create
    defaults:   { _controller: AppBundle:Article:create }
    
article_update:
    path:       /article/update/{id}
    defaults:   { _controller: AppBundle:Article:update }
    requirements:
        id:         '\d+'
        
article_show:
    path:       /article/{id}/{name}
    defaults:   { _controller: AppBundle:Article:show }
    requirements:
        id:         '\d+'